### ISSUE TITLE
Crash on Wallet Restore

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#23]
App crashes when generating a list of files from the downloads directory.

java.lang.NullPointerException: Attempt to get length of null array
    at de.schildbach.wallet.ui.WalletActivity.prepareRestoreWalletDialog(WalletActivity.java:570) ~[na:0.0]
    at de.schildbach.wallet.ui.WalletActivity.onPrepareDialog(WalletActivity.java:451) ~[na:0.0]
    at android.app.Activity.onPrepareDialog(Activity.java:3386) ~[na:0.0]
    at android.app.Activity.showDialog(Activity.java:3450) ~[na:0.0]
    at android.app.Activity.showDialog(Activity.java:3400) ~[na:0.0]
    at de.schildbach.wallet.ui.WalletActivity.onContextItemSelected(WalletActivity.java:1019) ~[na:0.0]
    at android.app.Activity.onMenuItemSelected(Activity.java:2934) ~[na:0.0]
    at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403) ~[na:0.0]
    at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:167) ~[na:0.0]
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100) ~[na:0.0]
    at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100) ~[na:0.0]
    at com.android.internal.policy.PhoneWindow$DialogMenuCallback.onMenuItemSelected(PhoneWindow.java:5013) ~[na:0.0]
    at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:761) ~[na:0.0]
    at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152) ~[na:0.0]
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:904) ~[na:0.0]
    at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:894) ~[na:0.0]
    at com.android.internal.view.menu.MenuDialogHelper.onClick(MenuDialogHelper.java:167) ~[na:0.0]
    at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1108) ~[na:0.0]
    at android.widget.AdapterView.performItemClick(AdapterView.java:310) ~[na:0.0]
    at android.widget.AbsListView.performItemClick(AbsListView.java:1145) ~[na:0.0]
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3066) ~[na:0.0]
    at android.widget.AbsListView$3.run(AbsListView.java:3903) ~[na:0.0]
    at android.os.Handler.handleCallback(Handler.java:739) ~[na:0.0]
    at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
    at android.os.Looper.loop(Looper.java:148) ~[na:0.0]
    at android.app.ActivityThread.main(ActivityThread.java:5439) ~[na:0.0]
    at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) ~[na:0.0]
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) ~[na:0.0]

**Comment by joshafest** [comment]
Have some data to get restored?

**Comment by HashEngineering** [comment]
This bug is due to permissions of getting the backup directory (downloads).  It will work, if the backup function is used first.

**Comment by HashEngineering** [comment]
Fixed in v4.65.12.1Q.
