### ISSUE TITLE
Crash at Unknown Place (ModernAsyncTask)

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#29]
```
java.lang.IllegalStateException: Cannot execute task: the task is already running.
at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414)
at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219)
at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232)
at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88)
at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464)
at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48)
at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:154)
at android.app.ActivityThread.main(ActivityThread.java:6176)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
```

**Comment by HashEngineering** [comment]
18 Reports received (via email) + 2 Reports (via Google Play).

**Comment by HashEngineering** [comment]
This crash could be coming from one of eight places in the app.  It may be eliminated from future versions because support v4 won't be used as much.  It may appear again, however.

**Comment by HashEngineering** [comment]
`09:59:13.807 [dash-privatesend] MasternodeSync - CMasternodeSync::Process() - tick 7 RequestedMasternodeAttempt 0 RequestedMasternodeAssets 1 nSyncProgress 0.0
09:59:13.810 [dash-privatesend] DarkSendPool - closing thread: dash-privatesend
09:59:13.814 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6121) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779) ~[na:0.0]
09:59:13.875 [PeerGroup Thread] PeerGroup - 500 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, last 39.06 kilobytes per sec
09:59:14.878 [PeerGroup Thread] PeerGroup - 482 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, last 37.66 kilobytes per sec
09:59:14.933 [NioClientManager] Peer - [144.217.5.197]:9999: Received unhandled message: org.bitcoinj.core.SendHeadersMessage@e0108d2
09:59:14.940 [NioClientManager] Peer - [bandwidth] 0.15604114532470703 MiB in 5 s:31.491157432499016 KB/s
09:59:14.950 [NioClientManager] Peer - [34.193.23.211]:9999: Received unhandled message: org.bitcoinj.core.SendHeadersMessage@b8ceda3
09:59:14.956 [NioClientManager] Peer - [bandwidth] 0.1578836441040039 MiB in 5 s:31.762839206777997 KB/s
09:59:14.974 [NioClientManager] Peer - [bandwidth] 0.1597270965576172 MiB in 5 s:32.02046728171496 KB/s
09:59:14.987 [NioClientManager] Peer - [bandwidth] 0.1616048812866211 MiB in 5 s:32.3146647993556 KB/s
09:59:14.993 [NioClientManager] Peer - [23.175.0.113]:9999: Received unhandled message: org.bitcoinj.core.SendHeadersMessage@a7b08a0`

**Comment by HashEngineering** [comment]
```
12:18:00.750 [NioClientManager] Peer - [104.207.150.178]:9999: Received unhandled message: org.bitcoinj.core.SendHeadersMessage@1e01d9b
12:18:01.115 [NioClientManager] Peer - [bandwidth] 0.003849029541015625 MiB in 0 s:4.0136519857433814 KB/s
12:18:02.517 [NioClientManager] Peer - [bandwidth] 0.005558013916015625 MiB in 2 s:2.3873348364093956 KB/s
12:18:03.616 [NioClientManager] Peer - [bandwidth] 0.0071563720703125 MiB in 3 s:2.1039692793568765 KB/s
12:18:04.202 [NioClientManager] Peer - [bandwidth] 0.008955001831054688 MiB in 4 s:2.253605769230769 KB/s
12:18:04.232 [dash-privatesend] MasternodeSync - CMasternodeSync::Process() - tick 7 RequestedMasternodeAttempt 0 RequestedMasternodeAssets 1 nSyncProgress 0.0
12:18:04.233 [dash-privatesend] DarkSendPool - closing thread: dash-privatesend
12:18:04.236 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:168) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5885) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:819) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:709) ~[na:0.0]
12:18:04.302 [NioClientManager] SporkManager - spork - new 687c96e82b08cd20737f5cf23b566567f66d21b4e89b661c9f07641a7c64009d ID 10000 Time 1439575011 bestHeight698627
12:18:04.316 [NioClientManager] SporkManager - spork - new 0bef49d272c6f7b207983ff71497764d04b85f61245f2ba2668f6221e97b27bc ID 10001 Time 1488778936 bestHeight698627
12:18:04.326 [NioClientManager] SporkManager - spork - new 679a898a1903e8ae1e040d992b42f6bb837f7bfc778d44d6fda499458904b065 ID 10002 Time 1457708905 bestHeight698627
12:18:04.343 [NioClientManager] SporkManager - spork - new dfaa4dd265801d7d7b496d79ba38f722e1781be3f8c7cec2fcf579ecc93edff7 ID 10003 Time 1423712147 bestHeight698627
12:18:04.351 [NioClientManager] SporkManager - spork - new c52ba61a97303af15099eae71007e66dc2b2f77986faaf7f7b5f22e794e64780 ID 10004 Time 1450989417 bestHeight698627
12:18:04.360 [NioClientManager] SporkManager - spork - new eef0e1bdde3dd55182bacc534b05c24a71a26737bc1b2428382df51740bb2136 ID 10005 Time 1423846275 bestHeight698627
12:18:04.369 [NioClientManager] SporkManager - spork - new 679d531c58151753859f376dcb03cb55590ff9e3dec2012a14f5b46877cea860 ID 10007 Time 1490493492 bestHeight698627
12:18:04.375 [NioClientManager] SporkManager - spork - new a54d4a5c06e921095983eecff0be6dc2590b9a4b32f28cab17b64a47f08a3a58 ID 10008 Time 1488040706 bestHeight698627
12:18:04.383 [NioClientManager] SporkManager - spork - new da37741356c412f0d12583fcc6fc80383de97e60796ba3743f664d870210d73d ID 10009 Time 1486939593 bestHeight698627
12:18:04.390 [NioClientManager] SporkManager - spork - new 3b2f40ca7ca68189a90d24c1e8798634964bb6c6cfee9aad50c8777f1ed77182 ID 10012 Time 1486338444 bestHeight698627
12:18:04.396 [NioClientManager] SporkManager - spork - new 2b3418b627e36e47f3a9636c0bde33c610bedbf00247300adaa21a3e75642064 ID 10013 Time 1490347139 bestHeight698627
```

**Comment by HashEngineering** [comment]
From Google Play - Crashes:

```
java.lang.IllegalStateException: 
  at android.support.v4.content.ModernAsyncTask.executeOnExecutor (ModernAsyncTask.java:414)
  at android.support.v4.content.AsyncTaskLoader.executePendingTask (AsyncTaskLoader.java:219)
  at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled (AsyncTaskLoader.java:232)
  at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled (AsyncTaskLoader.java:88)
  at android.support.v4.content.ModernAsyncTask.finish (ModernAsyncTask.java:464)
  at android.support.v4.content.ModernAsyncTask.access$400 (ModernAsyncTask.java:48)
  at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage (ModernAsyncTask.java:483)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6247)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:872)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:762)
```

**Comment by HashEngineering** [comment]
App crashed a few seconds after starting for the first time. 


```
15:15:21.165 [PeerGroup Thread] PeerGroup - 939 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, last 73.36 kilobytes per sec
15:15:21.461 [dash-privatesend] MasternodeSync - CMasternodeSync::Process() - tick 7 RequestedMasternodeAttempt 0 RequestedMasternodeAssets 1 nSyncProgress 0.0
15:15:21.463 [dash-privatesend] DarkSendPool - closing thread: dash-privatesend
15:15:21.473 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6682) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410) ~[na:0.0]
15:15:22.134 [NioClientManager] Peer - [bandwidth] 0.3121805191040039 MiB in 4 s:64.126951165998 KB/s
15:15:22.138 [NioClientManager] NioClientManager - Connected to dnsseed.dash.org/45.32.19.153:9999
15:15:22.139 [NioClientManager] Peer - Announcing to dnsseed.dash.org/45.32.19.153:9999 as: /DashJ:0.14.3-12.1/Dash Wallet:4.65.12.1U/
15:15:22.140 [NioClientManager] NioClientManager - Connected to dnsseed.dashdot.io/178.33.98.72:9999
15:15:22.141 [NioClientManager] Peer - Announcing to dnsseed.dashdot.io/178.33.98.72:9999 as: /DashJ:0.14.3-12.1/Dash Wallet:4.65.12.1U/
15:15:22.147 [NioClientManager] Peer - [bandwidth] 0.3139171600341797 MiB in 4 s:64.31596075930372 KB/s
15:15:22.152 [NioClientManager] NioClientManager - Connected to dnsseed.dash.org/34.206.155.38:9999
15:15:22.153 [NioClientManager] Peer - Announcing to dnsseed.dash.org/34.206.155.38:9999 as: /DashJ:0.14.3-12.1/Dash Wallet:4.65.12.1U/
15:15:22.155 [NioClientManager] PeerGroup - [178.33.98.72]:9999: Peer died      (4 connected, 2 pending, 6 max)
15:15:22.165 [PeerGroup Thread] PeerGroup - 982 blocks/sec, 0 tx/sec, 0 pre-filtered tx/sec, last 76.72 kilobytes per sec
15:15:22.181 [NioClientManager] SporkManager - spork - new 687c96e82b08cd20737f5cf23b566567f66d21b4e89b661c9f07641a7c64009d ID 10000 Time 1439575011 bestHeight498208
15:15:22.191 [NioClientManager] SporkManager - spork - new 0bef49d272c6f7b207983ff71497764d04b85f61245f2ba2668f6221e97b27bc ID 10001 Time 1488778936 bestHeight498208
15:15:22.200 [NioClientManager] SporkManager - spork - new 679a898a1903e8ae1e040d992b42f6bb837f7bfc778d44d6fda499458904b065 ID 10002 Time 1457708905 bestHeight498208
15:15:22.208 [NioClientManager] SporkManager - spork - new dfaa4dd265801d7d7b496d79ba38f722e1781be3f8c7cec2fcf579ecc93edff7 ID 10003 Time 1423712147 bestHeight498208
15:15:22.218 [NioClientManager] SporkManager - spork - new c52ba61a97303af15099eae71007e66dc2b2f77986faaf7f7b5f22e794e64780 ID 10004 Time 1450989417 bestHeight498208
15:15:22.226 [NioClientManager] SporkManager - spork - new eef0e1bdde3dd55182bacc534b05c24a71a26737bc1b2428382df51740bb2136 ID 10005 Time 1423846275 bestHeight498208
15:15:22.233 [NioClientManager] SporkManager - spork - new 679d531c58151753859f376dcb03cb55590ff9e3dec2012a14f5b46877cea860 ID 10007 Time 1490493492 bestHeight498208
15:15:22.241 [NioClientManager] SporkManager - spork - new a54d4a5c06e921095983eecff0be6dc2590b9a4b32f28cab17b64a47f08a3a58 ID 10008 Time 1488040706 bestHeight498208
15:15:22.248 [NioClientManager] SporkManager - spork - new da37741356c412f0d12583fcc6fc80383de97e60796ba3743f664d870210d73d ID 10009 Time 1486939593 bestHeight498208
15:15:22.255 [NioClientManager] Peer - [34.206.155.38]:9999: Got version=70206, subVer='/Dash Core:0.12.1.5/', services=0x5, time=2017-07-02 15:15:24, blocks=696633
15:15:22.256 [NioClientManager] PeerGroup - [34.206.155.38]:9999: New peer      (5 connected, 1 pending, 6 max)
15:15:22.260 [NioClientManager] Peer - [bandwidth] 0.31601619720458984 MiB in 5 s:63.314534521130895 KB/s
15:15:22.262 [NioClientManager] SporkManager - spork - new 3b2f40ca7ca68189a90d24c1e8798634964bb6c6cfee9aad50c8777f1ed77182 ID 10012 Time 1486338444 bestHeight498208
15:15:22.268 [NioClientManager] SporkManager - spork - new 2b3418b627e36e47f3a9636c0bde33c610bedbf00247300adaa21a3e75642064 ID 10013 Time 1490347139 bestHeight498208
```

**Comment by HashEngineering** [comment]
Happened right after first time launching the app.
```
06:33:37.495 [dash-privatesend] MasternodeSync - CMasternodeSync::Process() - tick 7 RequestedMasternodeAttempt 0 RequestedMasternodeAssets 1 nSyncProgress 0.0
06:33:37.497 [dash-privatesend] DarkSendPool - closing thread: dash-privatesend
06:33:37.504 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:241) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6217) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) ~[na:0.0]
06:33:37.552 [NioClientManager] SporkManager - spork - new 687c96e82b08cd20737f5cf23b566567f66d21b4e89b661c9f07641a7c64009d ID 10000 Time 1439575011 bestHeight690806
06:33:37.565 [NioClientManager] SporkManager - spork - new 0bef49d272c6f7b207983ff71497764d04b85f61245f2ba2668f6221e97b27bc ID 10001 Time 1488778936 bestHeight690806
06:33:37.574 [NioClientManager] SporkManager - spork - new 679a898a1903e8ae1e040d992b42f6bb837f7bfc778d44d6fda499458904b065 ID 10002 Time 1457708905 bestHeight690806
06:33:37.583 [NioClientManager] SporkManager - spork - new dfaa4dd265801d7d7b496d79ba38f722e1781be3f8c7cec2fcf579ecc93edff7 ID 10003 Time 1423712147 bestHeight690806
06:33:37.591 [NioClientManager] SporkManager - spork - new c52ba61a97303af15099eae71007e66dc2b2f77986faaf7f7b5f22e794e64780 ID 10004 Time 1450989417 bestHeight690806
06:33:37.601 [NioClientManager] SporkManager - spork - new eef0e1bdde3dd55182bacc534b05c24a71a26737bc1b2428382df51740bb2136 ID 10005 Time 1423846275 bestHeight690806
06:33:37.609 [NioClientManager] Peer - [bandwidth] 0.05165576934814453 MiB in 4 s:10.79059726897185 KB/s
06:33:37.611 [NioClientManager] SporkManager - spork - new 679d531c58151753859f376dcb03cb55590ff9e3dec2012a14f5b46877cea860 ID 10007 Time 1490493492 bestHeight690806
06:33:37.620 [NioClientManager] SporkManager - spork - new a54d4a5c06e921095983eecff0be6dc2590b9a4b32f28cab17b64a47f08a3a58 ID 10008 Time 1488040706 bestHeight690806
06:33:37.630 [NioClientManager] SporkManager - spork - new da37741356c412f0d12583fcc6fc80383de97e60796ba3743f664d870210d73d ID 10009 Time 1486939593 bestHeight690806
06:33:37.638 [NioClientManager] SporkManager - spork - new 3b2f40ca7ca68189a90d24c1e8798634964bb6c6cfee9aad50c8777f1ed77182 ID 10012 Time 1486338444 bestHeight690806
06:33:37.646 [NioClientManager] SporkManager - spork - new 2b3418b627e36e47f3a9636c0bde33c610bedbf00247300adaa21a3e75642064 ID 10013 Time 1490347139 bestHeight69080
```

**Comment by HashEngineering** [comment]
First Report of this bug was on Feb 23, 2017 with 4.65.12.1M
```
16:44:31.325 [dash-privatesend] DarkSendPool - closing thread: dash-privatesend
16:44:31.336 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalStateException: Cannot execute task: the task is already running.
	at android.support.v4.content.ModernAsyncTask.executeOnExecutor(ModernAsyncTask.java:414) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.executePendingTask(AsyncTaskLoader.java:219) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader.dispatchOnCancelled(AsyncTaskLoader.java:232) ~[na:0.0]
	at android.support.v4.content.AsyncTaskLoader$LoadTask.onCancelled(AsyncTaskLoader.java:88) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:464) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48) ~[na:0.0]
	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:150) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5621) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684) ~[na:0.0]
16:44:35.368 [main] WalletApplication - === starting app using configuration: prod, org.darkcoin.production
```

**Comment by HashEngineering** [comment]
This error may not be present in v5.14 as it doesn't use the android.support.v4 for AsyncTask related classes.

**Comment by HashEngineering** [comment]
v5.14.1

```
java.lang.IllegalStateException: 
  at android.os.AsyncTask.executeOnExecutor (AsyncTask.java:602)
  at android.content.AsyncTaskLoader.executePendingTask (AsyncTaskLoader.java:235)
  at android.content.AsyncTaskLoader.dispatchOnCancelled (AsyncTaskLoader.java:248)
  at android.content.AsyncTaskLoader$LoadTask.onCancelled (AsyncTaskLoader.java:103)
  at android.os.AsyncTask.finish (AsyncTask.java:658)
  at android.os.AsyncTask.-wrap1 (AsyncTask.java)
  at android.os.AsyncTask$InternalHandler.handleMessage (AsyncTask.java:677)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6123)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:867)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:757)
```

**Comment by HashEngineering** [comment]
Perhaps the first time this app is run, there are two of the same task being executed.  But this does not happen the 2nd time or later when the app is run on the device.

**Comment by HashEngineering** [comment]
This error may be due to the presense of a MasternodeSync loader.  It was removed from v5.17.  This loader was there to monitor sync status (mainly for sporks).
