### ISSUE TITLE
OutOfMemory Crash

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#34]
A common crash.  Is there a solution?
```

java.lang.OutOfMemoryError: 
  at java.util.ArrayList.add(ArrayList.java:118)
  at org.bitcoinj.wallet.Protos$Transaction$Builder.addTransactionOutput(Protos.java:10853)
  at org.bitcoinj.wallet.WalletProtobufSerializer.makeTxProto(WalletProtobufSerializer.java:272)
  at org.bitcoinj.wallet.WalletProtobufSerializer.walletToProto(WalletProtobufSerializer.java:151)
  at org.bitcoinj.wallet.WalletProtobufSerializer.writeWallet(WalletProtobufSerializer.java:123)
  at org.bitcoinj.wallet.Wallet.saveToFileStream(Wallet.java:1459)
  at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1273)
  at org.bitcoinj.wallet.Wallet.saveToFile(Wallet.java:1313)
  at de.schildbach.wallet.WalletApplication.protobufSerializeWallet(WalletApplication.java:422)
  at de.schildbach.wallet.WalletApplication.saveWallet(WalletApplication.java:395)
  at de.schildbach.wallet.service.BlockchainServiceImpl.onDestroy(BlockchainServiceImpl.java:773)
  at android.app.ActivityThread.handleStopService(ActivityThread.java:4093)
  at android.app.ActivityThread.access$2500(ActivityThread.java:222)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1903)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:158)
  at android.app.ActivityThread.main(ActivityThread.java:7229)
  at java.lang.reflect.Method.invoke(Native Method:0)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

This error occurs in many places according to Google Play.

**Comment by HashEngineering** [comment]
On Restore Wallet from Backup.
```
16:12:08.796 [main] CrashReporter - crashing because of uncaught exception
java.lang.OutOfMemoryError: null
	at de.schildbach.wallet.util.Crypto.decryptRaw(Crypto.java:275) ~[na:0.0]
	at de.schildbach.wallet.util.Crypto.decryptBytes(Crypto.java:242) ~[na:0.0]
	at de.schildbach.wallet.ui.WalletActivity.restoreWalletFromEncrypted(WalletActivity.java:851) ~[na:0.0]
	at de.schildbach.wallet.ui.WalletActivity.access$300(WalletActivity.java:96) ~[na:0.0]
	at de.schildbach.wallet.ui.WalletActivity$6.onClick(WalletActivity.java:496) ~[na:0.0]
	at com.android.internal.app.AlertController$ButtonHandler.handleMessage(AlertController.java:170) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:146) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:5598) ~[na:0.0]
	at java.lang.reflect.Method.invokeNative(Native Method) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Method.java:515) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099) ~[na:0.0]
	at dalvik.system.NativeStart.main(Native Method) ~[na:0.0]
```

**Comment by HashEngineering** [comment]
These issues were resolved for the most part.  There were memory leaks in DashJ.
