### ISSUE TITLE
TransactionTooLargeException (not from DASH)

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#49]
Android 7 and 7.0

```
java.lang.RuntimeException: 
  at android.app.ActivityThread$StopInfo.run (ActivityThread.java:4167)
  at android.os.Handler.handleCallback (Handler.java:751)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:154)
  at android.app.ActivityThread.main (ActivityThread.java:6692)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1468)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1358)
Caused by: android.os.TransactionTooLargeException: 
  at android.os.BinderProxy.transactNative (Native Method)
  at android.os.BinderProxy.transact (Binder.java:628)
  at android.app.ActivityManagerProxy.activityStopped (ActivityManagerNative.java:4132)
  at android.app.ActivityThread$StopInfo.run (ActivityThread.java:4159)
```

**Comment by HashEngineering** [comment]
https://stackoverflow.com/questions/39098590/android-os-transactiontoolargeexception-on-nougat/39747117#39747117

**Comment by HashEngineering** [comment]
https://github.com/guardian/toolargetool

**Comment by HashEngineering** [comment]
```
=== application info === 
Version: 5.14.2 (51420) 
Package: hashengineering.darkcoin.wallet 
Test/Prod: prod 
Timezone: Europe/Riga Time: 2017-08-24 22:04:21 
UTC Time of launch: 2017-08-24 22:02:21 
UTC Time of last update: 2017-08-24 21:53:43 
UTC Time of first install: 2017-08-24 21:53:43 
UTC Time of backup: none 
Network: org.darkcoin.production E
ncrypted: false 
Keychain size: 271 Transactions: 0 Inputs: 0 Outputs: 0 (spent: 0) 
Last block seen: 725778 (000000000000072ec6a312cca4edf0bb9e972d4625f4339d9232140ea44bc98b) 
Databases: address_book address_book-journal 
Contents of FilesDir /data/user/0/hashengineering.darkcoin.wallet/files: 2017-08-24 22:02:32 4096 files - 2017-08-24 21:53:47 663 key-backup-protobuf - 2017-08-24 22:02:32 23407 wallet-protobuf - 2017-08-24 09:34:29 45 fees.txt Contents of LogDir /data/user/0/hashengineering.darkcoin.wallet/app_log: 2017-08-24 21:53:46 4096 app_log - 2017-08-24 22:04:20 94078 wallet.log 

=== stack trace ===
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1810408 bytes 
at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3804) 
at android.os.Handler.handleCallback(Handler.java:751) 
at android.os.Handler.dispatchMessage(Handler.java:95) 
at android.os.Looper.loop(Looper.java:154) 
at android.app.ActivityThread.main(ActivityThread.java:6165) 
at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785) 

Caused by: android.os.TransactionTooLargeException: data parcel size 1810408 bytes at android.os.BinderProxy.transactNative(Native Method) 
at android.os.BinderProxy.transact(Binder.java:615) 
at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3658)
 at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3796) ... 7 more 

Cause: android.os.TransactionTooLargeException: data parcel size 1810408 bytes at android.os.BinderProxy.transactNative(Native Method) at android.os.BinderProxy.transact(Binder.java:615) at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3658) at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3796) at android.os.Handler.handleCallback(Handler.java:751)
 at android.os.Handler.dispatchMessage(Handler.java:95) at android.os.Looper.loop(Looper.java:154) at android.app.ActivityThread.main(ActivityThread.java:6165) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:895) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:785) 

=== device info === Device Model: MI 6 Android Version: 7.1.1 Android security patch level: 2017-05-01 ABIs: armeabi-v7a, armeabi Board: msm8998 Brand: Xiaomi Device: sagit Display: NMF26X Finger Print: Xiaomi/sagit/sagit:7.1.1/NMF26X/V8.2.2.0.NCAMIEC:user/release-keys Host: c3-miui-ota-bd80.bj ID: NMF26X Product: sagit Tags: release-keys Time: 1497017537000 Type: user User: builder Configuration: {1.0 247mcc2mnc [en_GB] ldltr sw360dp w360dp h620dp 480dpi nrml long port finger -keyb/v/h -nav/h s.25 themeChanged=0 themeChangedFlags=0} Screen Layout: size 2 long 32 Display Metrics: DisplayMetrics{density=3.0, width=1080, height=1920, scaledDensity=3.0, xdpi=428.625, ydpi=427.789} Memory Class: 256/512 Storage Encryption Status: 5 Bluetooth MAC: null Runtime: Dalvik 2.1.0 PUT ADDITIONAL COMMENTS TO THE TOP. DOWN HERE NOBODY WILL NOTICE.
```

**Comment by HashEngineering** [comment]
Android 7.0

```
12:59:14 [main] BlockchainServiceImpl - onTrimMemory(20) called
12:59:14 [main] CrashReporter - crashing because of uncaught exception
java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 3215336 bytes
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3832) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6247) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762) ~[na:0.0]
Caused by: android.os.TransactionTooLargeException: data parcel size 3215336 bytes
	at android.os.BinderProxy.transactNative(Native Method) ~[na:0.0]
	at android.os.BinderProxy.transact(Binder.java:615) ~[na:0.0]
	at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3678) ~[na:0.0]
	at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3824) ~[na:0.0]
	... 7 common frames omitted
```

Is it from OnTrimMemory?

**Comment by schildbach** [comment]
I'm seeing this a lot with Bitcoin Wallet too. Actually due to the growing number of Android 7.x installations it's now the top reported exception. I went through all onSaveInstanceState()s but none is saving more than a couple of hundred bytes. NetworkMonitorActivity currently leaks a couple of dozend instance state bytes per screen rotation. That's a bug that needs to be fixed, but it hardly accumulates to 1 MB.

On the other hand, I've not seen a single Android O report of this. I'm beginning to suspect that this is actually triggered by a framework bug that was fixed with O.

**Comment by HashEngineering** [comment]
@schildbach Thanks for having a look at this issue and leaving a comment.  I was wondering if some of the bugs I have in this wallet were common with Bitcoin Wallet or if my changes had created new bugs.

Some of the answers at this link:  https://stackoverflow.com/questions/39098590/android-os-transactiontoolargeexception-on-nougat/39747117#39747117 indicate that with Android 7, if the 1 MB limit is reached an exception is thrown.  On previous versions, the exception is not thrown.   Perhaps the same is true for Android O.  If that is true, then in certain cases for any device, the 1 MB limit could be reached, though your review of onSaveInstanceState()s did not reveal a cause.

This is an issue, like many of those reported by users and Google Play that doesn't happen to me on my devices.

**Comment by HashEngineering** [comment]
I checked the onSaveInstanceState methods by adding a log output and found that the amount of data saved is rather small.  

Perhaps the culprit is a different part of the app, a part that still uses transactions.  Perhaps an Intent?

**Comment by schildbach** [comment]
I believe this commit reduced the number of TransactionTooLargeExceptions a bit: 823d9f93b63eb2d6e339290f6763c7e8b7daaf47

I also went through all of the intents and the only one I have found is this: 3ab94deb501608683a5768f388858c4e30a03082

**Comment by HashEngineering** [comment]
https://github.com/bitcoin-wallet/bitcoin-wallet/issues/447
Resolved by Bitcoin Wallet

**Comment by Stouse49** [comment]
No reports for a month or so.  Closing out.
