### ISSUE TITLE
Crash with KeyboardResponsiveCoordinatorLayout [After Sending Coins]

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#85]
```
Samsung Galaxy S5 (kltevzw), 2048MB RAM, Android 6.0
LGE LG K7 (m1), 1024MB RAM, Android 5.1


java.lang.NullPointerException: 
  at de.schildbach.wallet.ui.widget.KeyboardResponsiveCoordinatorLayout$1$1.run (KeyboardResponsiveCoordinatorLayout.java:81)
  at android.os.Handler.handleCallback (Handler.java:739)
  at android.os.Handler.dispatchMessage (Handler.java:95)
  at android.os.Looper.loop (Looper.java:158)
  at android.app.ActivityThread.main (ActivityThread.java:7224)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1230)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1120)
```

From an email Crash Report - from logs, appears to happen after sending coins:
```

=== device info ===

Device Model: SM-G900V
Android Version: 6.0.1
Android security patch level: 2016-06-01
ABIs: armeabi-v7a, armeabi

=== stack trace ===

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
at de.schildbach.wallet.ui.widget.KeyboardResponsiveCoordinatorLayout$1$1.run(KeyboardResponsiveCoordinatorLayout.java:81)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

**Comment by HashEngineering** [comment]
This is the line that has the exception:
https://github.com/HashEngineering/dash-wallet/blob/master/wallet/src/de/schildbach/wallet/ui/widget/KeyboardResponsiveCoordinatorLayout.java#L81

This is happening because `viewToHide == null`, but line 76 checks for that!  Perhaps something else is going on.

**Comment by HashEngineering** [comment]
@sambarboza 
Another report has come in.  This may be a serious bug on some platforms.
