### ISSUE TITLE
Paper Wallet Sweep results in Crash (from Sweeping Dust)

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#86]
```
02:30:12 [backgroundThread] RequestWalletBalanceTask - problem querying unspent outputs
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:0.0]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334) ~[na:0.0]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196) ~[na:0.0]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178) ~[na:0.0]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356) ~[na:0.0]
	at java.net.Socket.connect(Socket.java:605) ~[na:0.0]
	at de.schildbach.wallet.ui.send.RequestWalletBalanceTask$1.run(RequestWalletBalanceTask.java:142) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.os.HandlerThread.run(HandlerThread.java:61) ~[na:0.0]
02:30:12 [NioClientManager] Peer - [bandwidth] 2.325381278991699 MiB in 9397 s:0.2533837949587255 KB/s
02:30:14 [NioClientManager] Peer - [bandwidth] 2.3288707733154297 MiB in 9399 s:0.2537052263641917 KB/s
02:30:15 [NioClientManager] Peer - [bandwidth] 2.332521438598633 MiB in 9401 s:0.2540588976996015 KB/s
02:30:16 [backgroundThread] RequestWalletBalanceTask - trying to request wallet balance from electrum.dash.siampm.com:50001: XjdLrVEz4shnx2NN8Xk2CrjvXi5tg1cNCF
02:30:17 [backgroundThread] RequestWalletBalanceTask - fetched 1 unspent outputs from electrum.dash.siampm.com:50001
02:30:17 [main] Wallet - Upgrade to HD wallets is required, attempting to do so.
02:30:17 [main] KeyChainGroup - Auto-upgrading pre-HD wallet to HD!
02:30:17 [main] KeyChainGroup - Instantiating new HD chain using oldest non-rotating private key (address: XjdLrVEz4shnx2NN8Xk2CrjvXi5tg1cNCF)
02:30:17 [main] MnemonicCode - PBKDF2 took 197.9 ms
02:30:17 [main] SweepWalletFragment - built wallet to sweep:
Wallet containing 0.00001709 DASH (spendable: 0.00001709 DASH) in:
  0 pending transactions
  1 unspent transactions
  0 spent transactions
  0 dead transactions
Last seen best block: 0 (time unknown): null

Keys:
Earliest creation time: 1970-01-01T00:00:00Z
  addr:XjdLrVEz4shnx2NN8Xk2CrjvXi5tg1cNCF  hash160:620fb1a6d3cd7fd265b5044f695d0e3e9597d0ef
Seed birthday: 0  [1970-01-01T00:00:00Z]
Key to watch:  xpub67uD6rFSGFwVbpJ2QYLnHKhL7sczkqwVW124vEb5843Wxq6QF1erqMBxkWivxMTkuxuqxvXynP6njfqYGBLQFJ8GXf8cFCP1zDqZk7FfGda


>>> UNSPENT:
0.00001709 DASH total value (sends 0.00 DASH and receives 0.00001709 DASH)
  confidence: Appeared in best chain at height -1, depth 0.
  89351a77cefad3758544053e7d7bd615e3da098856a3fc9dec74464e7827fcc0
  INCOMPLETE: No inputs!

02:30:17 [main] SweepWalletFragment - State:  Confirm Sweep:  walletToSweep: invalidwallet balance > 0: truefees: {PRIORITY=10000, ECONOMIC=1000, NORMAL=1000, ZERO=0}
02:30:18 [NioClientManager] Peer - [bandwidth] 2.3360795974731445 MiB in 9404 s:0.2543739944158628 KB/s
02:30:20 [NioClientManager] Peer - [bandwidth] 2.339613914489746 MiB in 9405 s:0.2547129608407863 KB/s
02:30:21 [NioClientManager] Peer - [bandwidth] 2.3430938720703125 MiB in 9407 s:0.2550525847782388 KB/s
02:30:23 [NioClientManager] Peer - [bandwidth] 2.346456527709961 MiB in 9409 s:0.2553653867787859 KB/s
02:30:26 [NioClientManager] Peer - [bandwidth] 2.349736213684082 MiB in 9412 s:0.2556414322895418 KB/s
02:30:26 [main] WalletFiles - Saving wallet; last seen block is height 826826, date 2018-02-25T02:27:17Z, hash 000000000000002f8a355d7bfb239a006c0b0f13ee876b2d8792fda2beb249a1
02:30:27 [main] WalletFiles - Save completed in 29.63 ms
02:30:27 [backgroundThread] SendCoinsOfflineTask - sending: SendRequest{emptyWallet=true, feePerKb=1000, ensureMinRequiredFee=true, signInputs=true, shuffleOutputs=true}
02:30:27 [backgroundThread] Wallet - Completing send tx with 1 outputs totalling 0.00 DASH and a fee of 0.00001 DASH/kB
02:30:27 [backgroundThread] Wallet -   emptying 0.00001709 DASH
02:30:27 [backgroundThread] Wallet -   completed:   a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
     in   PUSHDATA(72)[3045022100a94974af46c2fe991b1bb5375ae3a1effea5bad373040f14d5d16322aefffe1a022036b90e51d85b1b0bc9360ec357ccde790c9799a945b34679673186f5bfa0363101] PUSHDATA(33)[02ed8cd1e6c6f8c73e6e15ceeca0eb9603f139cfb3a1d02715e6a91453fe478168] 0.00001709 DASH
          outpoint:89351a77cefad3758544053e7d7bd615e3da098856a3fc9dec74464e7827fcc0:0 hash160:620fb1a6d3cd7fd265b5044f695d0e3e9597d0ef
     out  DUP HASH160 PUSHDATA(20)[dc4c7ebac1390eb6396043cb5cff18d5aec9597a] EQUALVERIFY CHECKSIG 0.00000709 DASH
     fee  0.00005208 DASH/kB, 0.00001 DASH for 192 bytes
     prps USER_PAYMENT

02:30:27 [backgroundThread] Wallet - commitTx of a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
02:30:27 [backgroundThread] Wallet -   marked 89351a77cefad3758544053e7d7bd615e3da098856a3fc9dec74464e7827fcc0:0 as spent by a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
02:30:27 [backgroundThread] Wallet -   89351a77cefad3758544053e7d7bd615e3da098856a3fc9dec74464e7827fcc0 prevtx <-unspent ->spent
02:30:27 [backgroundThread] Wallet - ->pending: a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
02:30:27 [backgroundThread] Wallet - Estimated balance is now: 0.00 DASH
02:30:27 [backgroundThread] SendCoinsOfflineTask - send successful, transaction committed: a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
02:30:27 [main] DefaultRiskAnalysis - TX considered non-standard due to output 0 violating rule DUST
02:30:27 [main] Wallet - Pending transaction was considered risky: Risky due to non-standard tx a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
  a2d79ae524994c6a0c46284e241348bb90c65600c5ae2035409bad801a46b53e
  updated: 2018-02-25T02:30:27Z
     in   PUSHDATA(72)[3045022100a94974af46c2fe991b1bb5375ae3a1effea5bad373040f14d5d16322aefffe1a022036b90e51d85b1b0bc9360ec357ccde790c9799a945b34679673186f5bfa0363101] PUSHDATA(33)[02ed8cd1e6c6f8c73e6e15ceeca0eb9603f139cfb3a1d02715e6a91453fe478168] 0.00001709 DASH
          outpoint:89351a77cefad3758544053e7d7bd615e3da098856a3fc9dec74464e7827fcc0:0 hash160:620fb1a6d3cd7fd265b5044f695d0e3e9597d0ef
     out  DUP HASH160 PUSHDATA(20)[dc4c7ebac1390eb6396043cb5cff18d5aec9597a] EQUALVERIFY CHECKSIG 0.00000709 DASH
     fee  0.00005208 DASH/kB, 0.00001 DASH for 192 bytes
     prps USER_PAYMENT

02:30:27 [main] Wallet - There are now 1 risk dropped transactions being kept in memory
02:30:27 [main] BlockchainServiceImpl - service start command: Intent { act=de.schildbach.wallet.service.broadcast_transaction cmp=hashengineering.darkcoin.wallet/de.schildbach.wallet.service.BlockchainServiceImpl launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }
02:30:27 [main] CrashReporter - crashing because of uncaught exception
java.lang.RuntimeException: Unable to start service de.schildbach.wallet.service.BlockchainServiceImpl@268a00c with Intent { act=de.schildbach.wallet.service.broadcast_transaction cmp=hashengineering.darkcoin.wallet/de.schildbach.wallet.service.BlockchainServiceImpl launchParam=MultiScreenLaunchParams { mDisplayId=0 mBaseDisplayId=0 mFlags=0 } (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.bitcoinj.core.Transaction.getHashAsString()' on a null object reference
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3787) ~[na:0.0]
	at android.app.ActivityThread.-wrap23(ActivityThread.java) ~[na:0.0]
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:102) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6823) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) ~[na:0.0]
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.bitcoinj.core.Transaction.getHashAsString()' on a null object reference
	at de.schildbach.wallet.service.BlockchainServiceImpl.onStartCommand(BlockchainServiceImpl.java:649) ~[na:0.0]
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:3770) ~[na:0.0]
	... 8 common frames omitted
```

**Comment by HashEngineering** [comment]
This bug is due to the dust limits used in dashj with the DefaultRiskAnalyzer class.

**Comment by HashEngineering** [comment]
This was fixed in:
https://github.com/HashEngineering/dashj/commit/aea3af41935657d23f8d5bb03ac06940cf328fd2

Need to check which version of Dash Wallet has this fix.
