### ISSUE TITLE
Crash:  Set Spending PIN

### ISSUE THREAD

**Issue by HashEngineering** [HashEngineering/dash-wallet#92]
```
11:16:17 [main] EncryptKeysDialogFragment - setting spending password
11:16:18 [Wallet autosave thread] WalletFiles - Background saving wallet; last seen block is height 710080, date 2017-07-27T07:32:22Z, hash 0000000000001500fd4c129a406f786fbd9997f204c262da4683b88765982247
11:16:20 [backgroundThread] KeyCrypterScrypt - Deriving key took 2.472 s for 65536 scrypt iterations.
11:16:20 [main] CrashReporter - crashing because of uncaught exception
java.lang.IllegalArgumentException: No key found for absolute path M/0H.
	at org.bitcoinj.crypto.DeterministicHierarchy.get(DeterministicHierarchy.java:89) ~[na:0.0]
	at org.bitcoinj.wallet.DeterministicKeyChain.encryptNonLeaf(DeterministicKeyChain.java:451) ~[na:0.0]
	at org.bitcoinj.wallet.DeterministicKeyChain.<init>(DeterministicKeyChain.java:420) ~[na:0.0]
	at org.bitcoinj.wallet.DeterministicKeyChain.toEncrypted(DeterministicKeyChain.java:993) ~[na:0.0]
	at org.bitcoinj.wallet.KeyChainGroup.encrypt(KeyChainGroup.java:509) ~[na:0.0]
	at org.bitcoinj.wallet.Wallet.encrypt(Wallet.java:1136) ~[na:0.0]
	at de.schildbach.wallet.ui.EncryptKeysDialogFragment$3$1.run(EncryptKeysDialogFragment.java:264) ~[na:0.0]
	at android.os.Handler.handleCallback(Handler.java:751) ~[na:0.0]
	at android.os.Handler.dispatchMessage(Handler.java:95) ~[na:0.0]
	at android.os.Looper.loop(Looper.java:154) ~[na:0.0]
	at android.app.ActivityThread.main(ActivityThread.java:6816) ~[na:0.0]
	at java.lang.reflect.Method.invoke(Native Method) ~[na:0.0]
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563) ~[na:0.0]
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451) ~[na:0.0]
```

**Comment by HashEngineering** [comment]
> Device Model: SM-J510MN
> Android Version: 7.1.1
> Android security patch level: 2017-08-01
> ABIs: armeabi-v7a, armeabi
> Board: MSM8916
> Brand: samsung

**Comment by HashEngineering** [comment]
Turns out this is due to a bug in dashj when encrypting a BIP44 keychain.  A fix has been found.

**Comment by HashEngineering** [comment]
This was fixed in dashj.
